server:
  port: "8080"
  env: "dev"

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "123456"
  name: "codexdb"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

kafka:
  brokers: ["localhost:9092"]
  topics:
    task: "codex-tasks"
    result: "codex-results"

cos:
  secretid: "your-cos-secret-id"
  secretkey: "your-cos-secret-key"
  region: "ap-shanghai"
  buckets:
    code: "codex-code"
    logs: "codex-logs"

k8s:
  namespace: "default"
  agentimage: "codex-swe:latest"
  serviceaccount: "codex-swe"

openai:
  apikey: "your-openai-api-key"

github:
  token: "your-github-token"