# Codex-like System CI/CD Workflow
# This workflow builds and tests the Codex-like system components

name: Codex-like System CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        pwd
        ls -la
        go mod download

    - name: Fix docker/distribution version
      run: |
        go get github.com/docker/distribution@v2.7.1
        go mod tidy

    - name: Build API server
      run: |
        mkdir -p bin
        go build -v -o bin/api cmd/main.go

    - name: Build worker
      run: |
        mkdir -p bin
        go build -v -o ../bin/worker main.go

    - name: Test
      run: go test -v ./internal/... ./utils/...

  agent-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Dockerfiles/swe/go
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Build swe
      run: go build -v .

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-build, agent-build]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        docker-compose version

    - name: Build with Docker Compose
      run: |
        cd backend
        docker-compose build

    - name: Build Worker Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfiles/worker/Dockerfile
        push: false
        tags: codex-worker:latest
        load: true

    - name: Build Agent Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfiles/swe/Dockerfile
        push: false
        tags: codex-swe:latest
        load: true
